#!/usr/bin/env bash

# shellcheck disable=SC1090,SC1091

# exit as soon as error occurs
set -e

# install minimal dependencies
sudo apt install -y \
    git \
    gnupg2 \
    ssh \
    pass

# set pauline endpoint
PAULINE="frf2lr@franzelin.duckdns.net"

# copy keys from pauline
SOURCE_DIR=".gnupg"
TARGET_DIR="${HOME}/${SOURCE_DIR}"
mkdir -p "${TARGET_DIR}"
scp -r ${PAULINE}:${SOURCE_DIR} "${TARGET_DIR}"

# copy password store
SOURCE_DIR=".local/share/password-store"
TARGET_DIR="${HOME}/${SOURCE_DIR}"
mkdir -p "${TARGET_DIR}"
scp -r ${PAULINE}:${SOURCE_DIR} "${TARGET_DIR}"

# copy dotfiles
SOURCE_DIR="workspace/dotfiles"
TARGET_DIR="${HOME}/${SOURCE_DIR}"
mkdir -p "${TARGET_DIR}"
scp -r ${PAULINE}:${SOURCE_DIR} "${TARGET_DIR}"
