#+TITLE: dotfiles
#+AUTHOR: Fabian Franzelin
#+EMAIL: fabian.franzelin@gmail.com
#+CREATOR: Fabian Franzelin
#+LANGUAGE: en
#+OPTIONS: auto-id:t H:4 broken_links:mark email:t ^:{}
#+KEYWORDS: dotfiles linux emacs configuration

#+html: <a href="https://www.gnu.org/software/emacs/"><img src="https://img.shields.io/badge/Emacs-31-brightgreen.svg?style=flat&logo=GNU%20Emacs&logoColor=white"/></a>
#+html: <a href="https://github.com/fabianfranzelin/dotfiles/actions/workflows/ci.yml"><img src="https://github.com/fabianfranzelin/dotfiles/actions/workflows/ci.yml/badge.svg?branch=nightly"/></a>
#+html: <a href="https://github.com/fabianfranzelin/dotfiles/commits"><img src="https://img.shields.io/github/last-commit/fabianfranzelin/dotfiles"/></a>
#+html: <a href="https://github.com/fabianfranzelin/dotfiles/blob/nightly/LICENSE"><img src="https://img.shields.io/github/license/fabianfranzelin/dotfiles"/></a>

* System Configuration

In this repository, I gather my system configurations that allow me to have
a consistent computing experience over multiple Linux machines.

It configures three main tools: [[https://www.gnu.org/software/emacs/][GNU Emacs]], [[https://zsh.sourceforge.io/][ZSH]], and [[http://docs.qtile.org/en/stable/][Qtile]].

I use [[https://www.gnu.org/software/stow/][GNU Stow]] to install my configuration files on my Linux
distributions. Everything can be rolled out by calling the main
configure script of the repository


#+begin_src shell
./configure -i
#+end_src

** Overlay Directories

Additional dotfiles repositories (e.g. work-specific configurations) can be
integrated using the =--overlay-dir= option. An overlay directory is stowed on
top of the personal dotfiles and its =configure= script is executed
automatically if present.

#+begin_src shell
./configure -i --overlay-dir ../dotfiles-work
#+end_src

Multiple overlays can be specified:

#+begin_src shell
./configure -i --overlay-dir ../dotfiles-work --overlay-dir ../dotfiles-other
#+end_src

An overlay repository should follow the same directory structure as this
repository (stow-compatible, mirroring =$HOME=). Place a =.stow-local-ignore=
file and an executable =configure= script at its root for any overlay-specific
setup steps.

* Beyond Configurations

+ [[file:examples/README.org][Examples: Python, C++, org, Typescript/React]]
+ [[file:docs/content/index.org][Docs with org-mode and published as HTML on Github pages]]
+ [[file:.config/emacs/README.org][How to build Emacs 30 with tree-sitter]]
