# https://superuser.com/questions/624343/keep-gnupg-credentials-cached-for-entire-user-session
# https://superuser.com/questions/1075404/how-can-i-restart-gpg-agent
# default-cache-ttl 600 # 10 minutes
default-cache-ttl 28800 # 20 minutes
# max-cache-ttl 7200 # 2 hours
max-cache-ttl 28800 # 8 hours
# make the console pinentry the default
# https://superuser.com/questions/520980/how-to-force-gpg-to-use-console-mode-pinentry-to-prompt-for-passwords
pinentry-program /usr/bin/pinentry-curses