#!/usr/bin/env sh

aos_create_venv() {
    (
        cd "${HOME}/workspace/aos" || exit 1
        VIRTUALENV_NAME="aos"
        VIRTUALENV_ACTIVATE_FILEPATH="${HOME}/.virtualenvs/${VIRTUALENV_NAME}/bin/activate"

        if [ ! -f "${VIRTUALENV_ACTIVATE_FILEPATH}" ]; then
            echo "Create virtualenv ${VIRTUALENV_NAME}"
            python3 -m venv "${HOME}/.virtualenvs/${VIRTUALENV_NAME}"
        fi

        echo "Activate virtualenv"

        # shellcheck disable=SC1090
        . "${VIRTUALENV_ACTIVATE_FILEPATH}"
        python3 -m pip install --upgrade pip wheel setuptools

        # install command line tool
        python3 -m pip install "_tools/aos_cli"
        # python3 -m pip install -r "_tools/docker/aos_user_ubuntu2004/requirements.txt"
        # python3 -m pip install -r "_tools/docker/aos_dev_ubuntu2004/requirements.txt"

        # Workarounds
        # python3 -m pip install fasteners jsonschema pytz

        # install stuff for sphinx builds
        # python3 -m pip install git+https://github.boschdevcloud.com/FRF2LR/py_sphinx_docs.git

        # # other stuff that helps working
        # python3 -m pip install ipdb ipython

        deactivate
    )
}
