#!/usr/bin/env sh

aos_create_venv() {
    (
        cd "${HOME}/workspace/aos_base" || exit 1
        VIRTUALENV_NAME="aos_base"
        VIRTUALENV_ACTIVATE_FILEPATH="${HOME}/.virtualenvs/${VIRTUALENV_NAME}/bin/activate"

        if [ ! -f "${VIRTUALENV_ACTIVATE_FILEPATH}" ]; then
            echo "Create virtualenv ${VIRTUALENV_NAME}"
            python3 -m venv "${HOME}/.virtualenvs/${VIRTUALENV_NAME}"
        fi

        echo "Activate virtualenv"

        # shellcheck disable=SC1090
        . "${VIRTUALENV_ACTIVATE_FILEPATH}"
        python3 -m pip install --upgrade pip wheel setuptools pbr
        python3 -m pip install -r "./_tools/docker/aos_user_osd6/requirements.txt"
        python3 -m pip install -r "./_tools/docker/aos_dev_osd6/requirements.txt"

        # this is the minimum version required by fmt
        python3 -m pip install markupsafe==2.0
        pipx install poetry==1.2.1

        # for some reason, these packages are required to import rosbag
        python3 -m pip install pycryptodomex gnupg rospkg

        # for some other reason empy is also missing
        python3 -m pip install empy

        # install dependencies for the manifest manipulation tool
        python3 -m pip install argcomplete

        # install stuff for sphinx builds
        python3 -m pip install git+https://github.boschdevcloud.com/FRF2LR/py_sphinx_docs.git

        # other stuff that helps working
        python3 -m pip install ipdb ipython

        # language server in venv
        python3 -m pip install \
                virtualenv \
                epc \
                ptvsd \
                black \
                isort \
                yamllint \
                mdformat \
                cmake_language_server \
                "python-lsp-server[all]" \
                pylsp-mypy \
                esbonio \
                robotframework-tidy

        deactivate

        # install yarn
        npm install -g yarn
    )
}
