#!/usr/bin/env sh

aos_run_container() {
    docker run -it --rm \
           --net host \
           -e http_proxy \
           -e https_proxy \
           -e USER \
           -e BOSCH_USER \
           -e BITBUCKET_TOKEN \
           -e ARTIFACTORY_APIKEY \
           -e DISPLAY \
           -e CONAN_USER_HOME=/tmp/user/ \
           -u $(id -u):$(id -g) \
           -v "${HOME}/workspace/aos_base:/tmp/user/aos_base" \
           -v "${HOME}/.conan:/tmp/user/.conan" \
           -v "/var/tmp/conan_download_cache:/var/tmp/conan_download_cache" \
           -v "/var/tmp/ccache:/var/tmp/ccache" \
           -v "${HOME}/.bash_history:/tmp/user/.bash_history" \
           -v "/var/run/docker.sock:/var/run/docker.sock" \
           -v "$HOME/.qnx:/tmp/user/.qnx" \
           -v "$HOME/.flexlmrc:/tmp/user/.flexlmrc" \
           -v "/tmp/.X11-unix:/tmp/.X11-unix" \
           -v "${XAUTHORITY}:/tmp/user/.Xauthority" \
           -v "${HOME}/.ssh:/tmp/user/.ssh" \
           -e "DEBIAN_FRONTEND=noninteractive" \
           --group-add sudo \
           --shm-size 4g \
           --workdir /tmp/user/aos_base \
           rb-dtr.de.bosch.com/aos/aos_dev_osd6
}
