#!/usr/bin/env sh

dt_run_container() {
    ./.devcontainer/run_container.py \
        -t venv \
        -v "/tmp/.X11-unix:/tmp/.X11-unix" \
        -v "${XAUTHORITY}:${HOME}/.Xauthority" \
        -v "${HOME}/.config/shell/.history:${HOME}/.bash_history" \
        -e "DEBIAN_FRONTEND=noninteractive" \
        -e "DISPLAY=$DISPLAY" \
        "$@" \
        /bin/bash
}
