#!/usr/bin/env bash
# shell: all

# shellcheck disable=SC1090,SC1091

install_npm()
{
    install_helpers
    __install_load_versions

    echo "Install npm dependencies via nvm"
    export NVM_DIR="${HOME}/.config/nvm"
    if [ ! -d "${NVM_DIR}" ]
    then
        echo "Downloading and installing nvm v${NVM_VERSION}"
        mkdir -p "${NVM_DIR}"
        wget -qO- "https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh" | bash
    fi

    # load nvm paths
    if [ -s "${NVM_DIR}/nvm.sh" ]
    then
        . "${NVM_DIR}/nvm.sh" || true
    fi

    if ! command -v nvm &> /dev/null
    then
        echo "Something went wrong with the installation of nvm. Please check 'https://github.com/nvm-sh/nvm' for details."
        return 1
    fi

    echo "Install Node.js v${NODE_VERSION}"
    nvm install "${NODE_VERSION}"
    nvm use "${NODE_VERSION}"

    if ! command -v npm &> /dev/null
    then
        echo "Something went wrong with the installation of npm via nvm. Please call 'nvm install ${NODE_VERSION} && nvm use ${NODE_VERSION}' manually."
        return 1
    fi

    # install lsp servers, linters, etc.
    npm install -g \
        yaml-language-server \
        bash-language-server \
        typescript \
        typescript-language-server \
        dockerfile-language-server-nodejs \
        jsonlint \
        vscode-langservers-extracted \
        prettier-json \
        eslint

    # install other npm packages
    npm install -g \
        yarn \
        @github/copilot-language-server

    # Setup workstation specific npm config
    link_host_config "${DOTFILES}/.config/npm" "npmrc" "npmrc" "npmrc.default"
}
