#!/usr/bin/env bash

install_zsh()
{
    #------------------------------------------------------------------------------#
    # install oh-my-zsh if required
    export ZSH="${HOME}/.local/share/oh-my-zsh"
    if [ ! -f "${ZSH}/oh-my-zsh.sh" ]
    then
        sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
        # This script creates a .zshrc file in your home directory. We
        # won't need it, since we have a preconfigured one in this repo
        rm "${HOME}/.zshrc"
    fi

    POWERLEVEL10K_HOME="${ZSH}/custom/themes/powerlevel10k"
    if [ ! -d "${POWERLEVEL10K_HOME}" ]
    then
        git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${POWERLEVEL10K_HOME}"
    fi

    ZSH_AUTOSUGGESTION_HOME="${ZSH}/custom/plugins/zsh-autosuggestions"
    if [ ! -d "${ZSH_AUTOSUGGESTION_HOME}" ]
    then
        git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_AUTOSUGGESTION_HOME}"
    fi

    ZSH_SYNTAX_HIGHLIGHTING="${ZSH}/custom/plugins/zsh-syntax-highlighting"
    if [ ! -d "${ZSH_SYNTAX_HIGHLIGHTING}" ]
    then
        git clone https://github.com/zsh-users/zsh-syntax-highlighting "${ZSH_SYNTAX_HIGHLIGHTING}"
    fi

    ZSH_YOU_SHOULD_USE="${ZSH}/custom/plugins/you-should-use"
    if [ ! -d "${ZSH_YOU_SHOULD_USE}" ]
    then
        git clone https://github.com/MichaelAquilina/zsh-you-should-use "${ZSH_YOU_SHOULD_USE}"
    fi
}
