#!/usr/bin/env bash

install_base() {
    echo -e "${__COLOR_INFO}INFO: Installing minimal required packages for setup...${__COLOR_RESET}"
    sudo apt-get install -y \
         python3-pip

    # Remove PyQt5 if installed via pip. This package is buggy. It is
    # installed afterwards again via Ubuntu package sources.
    # python3 -m pip uninstall PyQt5

    # Make sure that there is just one venv package installed. We do
    # this via pip
    sudo apt-get remove -y python3-venv

    # Update python setuptools to latest release from pypi
    python3 -m pip install --upgrade \
            pip \
            wheel \
	    setuptools

    sudo apt-get install -y \
         xclip \
         xsel \
         wl-clipboard \
         locate \
         apt-transport-https \
         python3-pyqt5 \
         zsh \
         direnv \
         gnome-keyring \
         openjdk-17-jdk \
         zip \
         wget \
         unzip \
         compton \
         nitrogen \
         dmenu \
         vim \
         ccache \
         gnuplot \
         pass \
         gnupg \
         terminator \
	 fzf \
         htop \
         ssh \
         sshpass \
         dos2unix \
	 openssl \
	 libssl-dev \
         scons \
         texlive-base \
         texlive-science \
         texlive-bibtex-extra \
         texlive-lang-german \
         texlive-luatex \
         biber \
         doxygen \
         evince \
         gcovr

    if ( __is_wsl )
    then
       # install wslview for xdg-open so that firefox calls are
       # forwarded to host system
       sudo apt-get install -y \
            wslu
    fi

    # install gtk tools
    if ( __is_linux )
    then
        sudo apt-get install -y \
             vlc \
             firefox \
             eog
    fi

    # additional python dependencies
    python3 -m pip install --upgrade \
            virtualenv \
            ptvsd \
            black \
            isort \
            yamllint \
            mdformat \
            cmake \
            cmake_language_server \
            "python-lsp-server[all]" \
            pylsp-mypy \
            python-lsp-black \
            esbonio==0.16.4 \
            robotframework-tidy \
            ipython \
            gitpython \
            pytest \
            jupyter

    # install pandoc
    PANDOC_VER="3.2"
    PANDOC_BIN="pandoc-${PANDOC_VER}-1-amd64.deb"
    PANDOC_URL="https://github.com/jgm/pandoc/releases/download/${PANDOC_VER}/${PANDOC_BIN}"
    (
        cd "/tmp"
        wget "${PANDOC_URL}"
        sudo dpkg -i "${PANDOC_BIN}"
    )

    #------------------------------------------------------------------------------#
    # install dependencies gdb
    (
        cd "/tmp"
        GLIBC_NAME="glibc-2.39"
        wget "https://ftp.gnu.org/gnu/libc/${GLIBC_NAME}.tar.gz"
        tar -zxf "${GLIBC_NAME}.tar.gz"
        mv -n "${GLIBC_NAME}" "${HOME}/.local/share"
    )

    #------------------------------------------------------------------------------#
    # install dependencies for vscode
    if ( __is_linux )
    then
        # note that vscode is mounted from Windows in WSL and not
        # installed via apt. Ignore when code cannot be found
        sudo apt-get install -y code || true
        if command -v snap > /dev/null
        then
            sudo snap install --classic code || true
        fi
    fi
}
