#!/usr/bin/env bash

install_zsh()
{
    sudo apt-get install -y \
        zsh

    #------------------------------------------------------------------------------#
    # install oh-my-zsh if required
    export ZSH="${HOME}/.local/share/oh-my-zsh"
    if [ ! -f "${ZSH}/oh-my-zsh.sh" ]
    then
        sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
        # This script creates a .zshrc file in your home directory. We
        # won't need it, since we have a preconfigured one in this repo
        rm "${HOME}/.zshrc"
    fi

    (
        # create relative link from home to oh-my-zsh
        cd "${HOME}" || exit 1
        echo "Create symbolic link for .oh-my-zsh"
        ln -sfn ".local/share/oh-my-zsh" ".oh-my-zsh"
    )

    POWERLEVEL10K_HOME="${ZSH}/custom/themes/powerlevel10k"
    if [ ! -d "${POWERLEVEL10K_HOME}" ]
    then
        git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${POWERLEVEL10K_HOME}"
    else
        (
            echo "Pull updates for powerlevel10k"
            cd "${POWERLEVEL10K_HOME}" || exit 1
            git pull
        )
    fi

    ZSH_AUTOSUGGESTION_HOME="${ZSH}/custom/plugins/zsh-autosuggestions"
    if [ ! -d "${ZSH_AUTOSUGGESTION_HOME}" ]
    then
        git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_AUTOSUGGESTION_HOME}"
    else
        (
            echo "Pull updates for autosuggestions"
            cd "${ZSH_AUTOSUGGESTION_HOME}" || exit 1
            git pull
        )
    fi

    ZSH_SYNTAX_HIGHLIGHTING="${ZSH}/custom/plugins/zsh-syntax-highlighting"
    if [ ! -d "${ZSH_SYNTAX_HIGHLIGHTING}" ]
    then
        git clone https://github.com/zsh-users/zsh-syntax-highlighting "${ZSH_SYNTAX_HIGHLIGHTING}"
    else
        (
            echo "Pull updates for syntax highlighting"
            cd "${ZSH_SYNTAX_HIGHLIGHTING}" || exit 1
            git pull
        )
    fi

    ZSH_YOU_SHOULD_USE="${ZSH}/custom/plugins/you-should-use"
    if [ ! -d "${ZSH_YOU_SHOULD_USE}" ]
    then
        git clone https://github.com/MichaelAquilina/zsh-you-should-use "${ZSH_YOU_SHOULD_USE}"
    else
        (
            echo "Pull updates for you should use"
            cd "${ZSH_YOU_SHOULD_USE}" || exit 1
            git pull
        )
    fi

    ZSH_AUTOCOMPLETION="${ZSH}/custom/plugins/zsh-autocomplete"
    if [ ! -d "${ZSH_AUTOCOMPLETION}" ]
    then
        git clone https://github.com/marlonrichert/zsh-autocomplete "${ZSH_AUTOCOMPLETION}"
    else
        (
            echo "Pull updates for autocompletion"
            cd "${ZSH_AUTOCOMPLETION}" || exit 1
            git pull
        )
    fi

    ZSH_COMPLETION="${ZSH}/completions"
    mkdir -p "${ZSH_COMPLETION}"
    (
        cd "${ZSH_COMPLETION}" || exit 1
        curl https://raw.githubusercontent.com/bazelbuild/bazel/master/scripts/zsh_completion/_bazel -o _bazel
    )

    echo "Make zsh the default shell"
    sudo chsh -s "$(which zsh)" "${USER}"
}
