#!/usr/bin/env sh

install_python_3_10()
{
    PYTHON_VERSION="3.10.16"
    echo "INFO: Install Python ${PYTHON_VERSION}"
    PYTHON_HOME="${HOME}/.cache/python_3_10"
    PYTHON_FILEPATH="${PYTHON_HOME}/bin/python3"

    # Install the right Python version for qtile (>=3.10)
    if [ ! -f "${PYTHON_FILEPATH}" ]; then
        (
            # Install Python
            TMP_PYTHON_SRC=$(mktemp -d)
            cd "${TMP_PYTHON_SRC}" || exit 1
            wget "http://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz"
            tar -zxvf "Python-${PYTHON_VERSION}.tgz"
            cd "Python-${PYTHON_VERSION}" || exit 1

            mkdir -p "${PYTHON_HOME}"
            ./configure --prefix="${PYTHON_HOME}"
            make -j"$(nproc)"
            make install
        )
    fi
}
