#!/usr/bin/env bash

create_venv_qtile()
{
    echo -e "${__COLOR_INFO}INFO: Create virtual environemnt for Install Qtile desktop manager${__COLOR_RESET}"
    PYTHON_HOME="${HOME}/.cache/python_3_10"
    PYTHON_FILEPATH="${PYTHON_HOME}/bin/python3"

    VIRTUALENV_NAME="qtile"
    VIRTUALENV_ACTIVATE_FILEPATH="${HOME}/.virtualenvs/${VIRTUALENV_NAME}/bin/activate"
    if [[ ! -f "${VIRTUALENV_ACTIVATE_FILEPATH}" ]]; then
        echo -e "Create virtualenv ${VIRTUALENV_NAME}"
        LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PYTHON_HOME}/lib
        ${PYTHON_FILEPATH} -m venv "${HOME}/.virtualenvs/${VIRTUALENV_NAME}"
    fi
        virtualenv_name="org"
    virtualenv_activate_filepath="${HOME}/.virtualenvs/${virtualenv_name}/bin/activate"
    if [[ ! -f "${virtualenv_activate_filepath}" ]]; then
        echo -e "Create virtualenv ${virtualenv_name}"
        python3 -m venv "${HOME}/.virtualenvs/${virtualenv_name}"
    fi
}

install_qtile()
{
    echo -e "${__COLOR_INFO}INFO: Install Qtile desktop manager${__COLOR_RESET}"

    # Create a Python virtual environment for qtile
    create_venv_qtile

    VIRTUALENV_NAME="qtile"
    VIRTUALENV_ACTIVATE_FILEPATH="${HOME}/.virtualenvs/${VIRTUALENV_NAME}/bin/activate"
    echo -e "Activate virtualenv"

    # shellcheck disable=SC1090
    . "${VIRTUALENV_ACTIVATE_FILEPATH}"
    python3 -m pip install --upgrade setuptools wheel pip

    # install qtile and its dependencies for this exact version
    python3 -m pip install --upgrade pip wheel setuptools
    python3 -m pip install --upgrade xcffib
    python3 -m pip install --upgrade --no-cache-dir cairocffi
    sudo apt-get install -y libpangocairo-1.0-0
    python3 -m pip install --upgrade git+https://github.com/qtile/qtile.git
    # Install dependencies for widgets
    python3 -m pip install --upgrade psutil pulsectl-asyncio dbus-next
    # For eglot
    python3 -m pip install "python-lsp-server[all]" ipython ipdb pylint mypy flake8 black isort

    deactivate

    # setup X and other tools
    if ( __is_linux )
    then
        echo -e "${__COLOR_INFO}INFO: Install X configs for Qtile${__COLOR_RESET}"

        # Create xsessions entry for qtile according to
        # https://docs.qtile.org/en/latest/manual/install/index.html#starting-qtile
        XSESSIONS_PATH="/usr/share/xsessions"
        if [ -d "${XSESSIONS_PATH}" ]; then
            QTILE_DESKTOP_FILE_PATH="${XSESSIONS_PATH}/qtile.desktop"
            if [ ! -f "${QTILE_DESKTOP_FILE_PATH}" ]; then
  	        echo "[Desktop Entry]
Name=Qtile
Comment=Qtile Session
Exec=startqtile
Type=Application
Keywords=wm;tiling" | sudo tee "${QTILE_DESKTOP_FILE_PATH}"
            else
  	        echo -e "${__COLOR_WARN}The file '${QTILE_DESKTOP_FILE_PATH}' already exists. Skip creation. ${__COLOR_RESET}"
            fi

            CUSTOM_DESKTOP_FILE_PATH="${XSESSIONS_PATH}/custom.desktop"
            if [ ! -f "${CUSTOM_DESKTOP_FILE_PATH}" ]; then
  	        echo "[Desktop Entry]
Name=Qtile
Comment=Qtile Session
Exec=/etc/X11/Xsession
Type=Application
Keywords=wm;tiling" | sudo tee "${CUSTOM_DESKTOP_FILE_PATH}"
            else
  	        echo -e "${__COLOR_WARN}The file '${CUSTOM_DESKTOP_FILE_PATH}' already exists. Skip creation. ${__COLOR_RESET}"
            fi

            # Update power management: ignore lid close
            # https://askubuntu.com/questions/15520/how-can-i-tell-ubuntu-to-do-nothing-when-i-close-my-laptop-lid
            LOGIND="/etc/systemd/logind.conf"
            if [ -f "${LOGIND}" ]
            then
                echo "Ignore when lid is closed (systemd)"
                echo "HandleLidSwitch=ignore" | sudo tee "${LOGIND}"
                echo "HandleLidSwitchExternalPower=ignore" | sudo tee "${LOGIND}"
                echo "HandleLidSwitchDocked=ignore" | sudo tee "${LOGIND}"

            fi
            UPOWER="/etc/UPower/UPower.conf"
            if [ -f "${UPOWER}" ]
            then
                echo "Ignore when lid is closed (upower)"
                sudo sed -i "s/IgnoreLid=false/IgnoreLid=true/g" "${UPOWER}"
            fi
        fi

        # Install rofi
        sudo apt-get install -y \
             rofi

        ROFI_POWER_MENU="${HOME}/.local/bin/rofi-power-menu"
        if [ ! -f "${ROFI_POWER_MENU}" ]
        then
            (
                # Install Rofi power menu
                TMP_SRC=$(mktemp -d)
                cd "${TMP_SRC}" || exit 1
                git clone https://github.com/jluttine/rofi-power-menu.git
                cd rofi-power-menu || exit 1
                cp rofi-power-menu "${ROFI_POWER_MENU}"
            )
        fi

        # install autorandr for automatic detection of screen setups.
        # Setup the desired screen layout with xrandr. Use autorandr
        # --save <name> to create a new screen profile. Use autorandr
        # --load <name> to load it again.
        sudo apt-get install -y \
             autorandr \
             brightnessctl

        # Make sure that you can run brightnessctl without sudo
        sudo usermod -a -G video "${USER}"
    fi
}
