#!/usr/bin/env bash
# shell: all

install_docker()
{
    if command -v docker > /dev/null
    then
        sudo usermod -a -G docker "${USER}"
        sudo chmod 660 "/var/run/docker.sock"
    fi

    # Install docker-credential-pass
    SYSTEM_ARCH=$(dpkg --print-architecture)
    DOCKER_CRED_PASS_VER="0.9.5"
    DOCKER_CRED_PASS_BIN="docker-credential-pass-v${DOCKER_CRED_PASS_VER}.linux-${SYSTEM_ARCH}"
    DOCKER_CRED_PASS_URL="https://github.com/docker/docker-credential-helpers/releases/download/v${DOCKER_CRED_PASS_VER}/${DOCKER_CRED_PASS_BIN}"
    DOCKER_CRED_PASS_PATH="${HOME}/.local/bin/docker-credential-pass"
    cd "/tmp" || exit 1
    wget "${DOCKER_CRED_PASS_URL}"
    chmod 755 "${DOCKER_CRED_PASS_BIN}"
    mv -f "${DOCKER_CRED_PASS_BIN}" "${DOCKER_CRED_PASS_PATH}"

    #------------------------------------------------------------------------------#
    # Hack: setup workstation specific config for docker using extra symlink
    (
        cd "${DOTFILES}/.docker" || exit 1
        TARGET_DOCKER_CONFIG="config-$(hostname).json"
        if [ -f "${TARGET_DOCKER_CONFIG}" ]; then
            ln -s -f "${TARGET_DOCKER_CONFIG}" "config.json"
        else
            echo -e "${__COLOR_INFO}No specific docker configuration for $(hostname) available. I'll leave it empty.${__COLOR_RESET}"
        fi
    )
}
