#!/usr/bin/env bash

# Install Termux:API from f-droid make sure that the locstion service
# is enabled for termux:api. Check the Android settings

install_termux()
{
    ###########################################################################
    #                                   Init                                  #
    ###########################################################################
    termux-setup-storage

    pkg update

    pkg install -y \
        emacs \
        git \
        openssl-tool \
        pass \
        gnupg \
        which \
        git-lfs \
        rsync \
        poppler \
        termux-api \
        sshpass \
        wget \
        termux-api \
        jq

    LOCAL_BIN="${HOME}/.local/bin"
    mkdir -p "${LOCAL_BIN}"
    export PATH=${PATH}:${LOCAL_BIN}

    ###########################################################################
    #                                   GPG                                   #
    ###########################################################################
    echo "======================================"
    echo "Install gpg"

    GPG_HOME="${HOME}/.gnupg"
    GPG_CONF="${GPG_HOME}/.gpg.conf"
    GPG_AGENT_CONF="${GPG_HOME}/.gpg-agent.conf"
    mkdir -p "${GPG_HOME}"
    echo "personal-digest-preferences SHA256
cert-digest-algo SHA256
default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
auto-key-locate keyserver
    keyserver hkp://pgp.mit.edu" | tee "${GPG_CONF}"
    echo "# https://superuser.com/questions/624343/keep-gnupg-credentials-cached-for-entire-user-session
# https://superuser.com/questions/1075404/how-can-i-restart-gpg-agent
# default-cache-ttl 600 # 10 minutes
default-cache-ttl 28800 # 20 minutes
# max-cache-ttl 7200 # 2 hours
max-cache-ttl 28800 # 8 hours
# make the console pinentry the default
# https://superuser.com/questions/520980/how-to-force-gpg-to-use-console-mode-pinentry-to-prompt-for-passwords
pinentry-program $(which pinentry-curses)
# this means clients like Emacs can get the password in their own way and push to gpg
# for this to work with Emacs, set epa-pinentry-mode to 'loopback in Emacs
allow-emacs-pinentry
    " | tee "${GPG_AGENT_CONF}"

    ###########################################################################
    #                               Termux-tools                              #
    ###########################################################################
    echo "======================================"
    echo "Install termux-tools"
    # https://github.com/elpraga/Termux-tools
    pkg install python poppler ghostscript

    (
        TMP_SRC=$(mktemp -d)
        cd "${TMP_SRC}" || exit 1
        git clone "https://github.com/elpraga/Termux-tools.git"
        cd "Termux-tools" || exit 1
        chmod u+x "termux-url-opener" "termux-file-editor"
        cp -f "termux-url-opener" "termux-file-editor" "${HOME}/.local/bin"
    ) ###########################################################################
    #                                   Bash                                  #
    ###########################################################################
    echo "======================================"
    echo "Install bashrc"

    BASHRC="${HOME}/.bashrc"
    echo "
export PASSWORD_STORE='${HOME}/.password-store'

alias e='emacs -nw --init-directory=\"${HOME}/workspace/dotfiles/.config/minimal-emacs\"'
alias en='emacs -nw --init-directory=\"${HOME}/workspace/dotfiles/.config/native-emacs\"'
alias dot='cd ${HOME}/workspace/dotfiles/'
alias pas='cd ${HOME}/.password-store/'
alias org='cd ${HOME}/workspace/org'

alias cp='cp -i -P'
alias mv='mv -i'
alias grep='grep --color=auto'

alias c='clear'
# macOS: --color=auto needed for coreutils
alias l='ls -1F --color=auto'
alias la='ls -1F --color=auto -a'
alias ll='ls -1F --color=auto -lh'
alias lla='ls -1F --color=auto -lha'

alias cp='cp -i -P'
alias mv='mv -i'
alias grep='grep --color=auto'

alias c='clear'
alias l='ls -1F --color=auto'
alias la='ls -1F --color=auto -a'
alias ll='ls -1F --color=auto -altrh'
alias lla='ls -1F --color=auto -lha'

alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
alias .6='cd ../../../../../..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

alias g='git'
alias unlock_key='pass usernames/public@github > /dev/null'
alias u='unlock_key'

alias pauline='sshpass -p \"$(pass passwords/frf2lr@pauline)\" ssh frf2lr@pauline'
alias p='sshpass -p \"$(pass passwords/frf2lr@pauline)\" ssh -t frf2lr@pauline \"emacsclient -nw -a emacs; exec \$SHELL -l\"'
    " | tee "${BASHRC}"
    ###########################################################################
    #                                   ssh                                  #
    ###########################################################################
    echo "======================================"
    echo "Install ssh"

    SSHCONFIG="${HOME}/.ssh/config"
    echo "
Host *
     ControlMaster	auto
     ControlPath	tramp.%C
     ControlPersist	no
     ServerAliveInterval 5

Match host pauline exec \"test \\\"\$(termux-wifi-connectioninfo | jq -r '.ssid')\\\" = \\\"Pauline\\\"\"
     Hostname 192.168.178.48
     Port 22
     ForwardAgent yes
     ForwardX11 yes
     ForwardX11Trusted yes
     AddressFamily inet
     Compression yes

     ControlMaster auto
     ControlPath ~/.ssh/socket/%r@%h-%p
     ControlPersist 3600

Host pauline
     Hostname franzelin.duckdns.org
     Port 22
     ForwardAgent yes
     ForwardX11 yes
     ForwardX11Trusted yes
     AddressFamily inet
     Compression yes

     ControlMaster auto
     ControlPath ~/.ssh/socket/%r@%h-%p
     ControlPersist 3600
    " | tee "${SSHCONFIG}"
    ###########################################################################
    #                                   Docker                               #
    ###########################################################################
    pkg install root-repo tsu -y
    pkg install docker docker-compose -y
}
