#!/usr/bin/env bash
# shell: all

install_docker()
{
    install_helpers
    __install_load_versions

    if command -v docker > /dev/null
    then
        sudo usermod -a -G docker "${USER}"
        sudo chmod 660 "/var/run/docker.sock"
    fi

    # Install docker-credential-pass
    local SYSTEM_ARCH
    SYSTEM_ARCH=$(__install_dpkg_arch)
    install_github_binary \
        "https://github.com/docker/docker-credential-helpers/releases/download/v${DOCKER_CRED_PASS_VER}/docker-credential-pass-v${DOCKER_CRED_PASS_VER}.linux-${SYSTEM_ARCH}" \
        "docker-credential-pass" "${DOCKER_CRED_PASS_VER}"

    # Setup workstation specific docker config
    (
        cd "${DOTFILES}/.docker" || exit 1
        local target_config="config-$(hostname).json"
        if [ -f "${target_config}" ]; then
            ln -s -f "${target_config}" "config.json"
        else
            echo -e "${__COLOR_INFO:-}No specific docker configuration for $(hostname) available.${__COLOR_RESET:-}"
        fi
    )
}
