#!/usr/bin/env bash
# shell: all

install_zsh()
{
    install_helpers
    sudo apt-get install -y \
        zsh

    #------------------------------------------------------------------------------#
    # install oh-my-zsh if required
    export ZSH="${HOME}/.local/share/oh-my-zsh"
    if [ ! -f "${ZSH}/oh-my-zsh.sh" ]
    then
        sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
        # This script creates a .zshrc file in your home directory. We
        # won't need it, since we have a preconfigured one in this repo
        rm "${HOME}/.zshrc"
    fi

    (
        # create relative link from home to oh-my-zsh
        cd "${HOME}" || exit 1
        echo "Create symbolic link for .oh-my-zsh"
        ln -sfn ".local/share/oh-my-zsh" ".oh-my-zsh"
    )

    # zsh plugins and themes
    git_clone_or_pull "https://github.com/romkatv/powerlevel10k.git" \
        "${ZSH}/custom/themes/powerlevel10k" --depth=1

    git_clone_or_pull "https://github.com/zsh-users/zsh-autosuggestions" \
        "${ZSH}/custom/plugins/zsh-autosuggestions"

    git_clone_or_pull "https://github.com/zsh-users/zsh-syntax-highlighting" \
        "${ZSH}/custom/plugins/zsh-syntax-highlighting"

    git_clone_or_pull "https://github.com/MichaelAquilina/zsh-you-should-use" \
        "${ZSH}/custom/plugins/you-should-use"

    git_clone_or_pull "https://github.com/marlonrichert/zsh-autocomplete" \
        "${ZSH}/custom/plugins/zsh-autocomplete"

    echo "Make zsh the default shell"
    sudo chsh -s "$(which zsh)" "${USER}"
}
