#!/usr/bin/env sh

# Linux unlock gnome keyring
function unlock-keyring ()
{
    read -rsp "Password: " pass
        export $(echo -n "$pass" | gnome-keyring-daemon --replace --unlock)
            unset pass

}