- id: '1758488499252'
  alias: Fabis Schreibtisch - An
  description: 'Turns on a power plug at 8:00 AM on weekdays. '
  triggers:
  - at: 08:00:00
    trigger: time
    id: Start working
  conditions:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Start working
      sequence:
      - action: switch.turn_on
        metadata: {}
        target:
          device_id: 2c680c927a635dca2b6704a9d8d15d09
        data: {}
  mode: single
- id: '1760733577087'
  alias: Familienbad - Heizkörper
  description: Sets heating to 22°C or Off based on a weekday/weekend schedule.
  triggers:
  - at: 05:45:00
    id: weekday_morning_on
    trigger: time
  - at: 08:00:00
    id: weekday_morning_off
    trigger: time
  - at: 07:00:00
    id: weekend_morning_on
    trigger: time
  - at: 09:30:00
    id: weekend_morning_off
    trigger: time
  - at: '18:30:00'
    id: evening_on
    trigger: time
  - at: '20:00:00'
    id: evening_off
    trigger: time
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: trigger
            id: weekday_morning_on
          - condition: time
            weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: and
          conditions:
          - condition: trigger
            id: weekend_morning_on
          - condition: time
            weekday:
            - sat
            - sun
        - condition: trigger
          id: evening_on
      sequence:
      - target:
          area_id: familienbad
          device_id: 75b7856de539d67a4d57d526f761dac0
        data:
          temperature: 22
          hvac_mode: heat
        action: climate.set_temperature
    - conditions:
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: trigger
            id:
            - weekday_morning_off
          - condition: time
            weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: and
          conditions:
          - condition: trigger
            id:
            - weekend_morning_off
          - condition: time
            weekday:
            - sat
            - sun
      sequence:
      - target:
          area_id: familienbad
          device_id: 75b7856de539d67a4d57d526f761dac0
        data:
          temperature: 20
          hvac_mode: heat
        action: climate.set_temperature
    - conditions:
      - condition: or
        conditions:
        - condition: trigger
          id: evening_off
      sequence:
      - target:
          area_id: familienbad
          device_id: 75b7856de539d67a4d57d526f761dac0
        data:
          hvac_mode: heat
          temperature: 18
        action: climate.set_temperature
  mode: single
- id: '1778187802092'
  alias: Waschmaschine Automatisch Aus
  description: ''
  use_blueprint:
    path: Fredrik81/powerplug-auto-shutdown.yaml
    input:
      power_sensor: sensor.strom_waschmaschine_power
      plug_switch: switch.strom_waschmaschine
      use_time_check: false
      enable_notification: false
      max_run_time: 10
      grace_period: 600
      watt_threshold: 1
- id: '1778189930269'
  alias: Fabis Schreibtisch - Aus
  description: ''
  use_blueprint:
    path: Fredrik81/powerplug-auto-shutdown.yaml
    input:
      power_sensor: sensor.shellyplugsg3_28372f2736c0_power
      plug_switch: switch.fabis_schreibtisch
      watt_threshold: 10
      use_time_check: false
      grace_period: 600
- id: '1778191572133'
  alias: Clean House When Everyone Leaves
  description: Starts Roborock when phones disconnect from home or specific repeater
  triggers:
  - entity_id:
    - device_tracker.pixel_8a
    to:
    - not_home
    for:
      hours: 0
      minutes: 5
      seconds: 0
    trigger: state
  conditions:
  - condition: time
    after: 09:00:00
    before: '19:00:00'
  - condition: template
    value_template: '{{ state_attr(''automation.clean_house_when_everyone_leaves'',
      ''last_triggered'').date() != now().date() }}'
  actions:
  - action: vacuum.start
    data: {}
    target:
      device_id: 8465f32e2059a8f994838f5c49ad6091
  mode: single
