- id: '1758488499252'
  alias: Fabis Schreibtisch
  description: Turns on a power plug at 7:30 AM and off at 12 AM on weekdays.
  triggers:
  - at: 07:30:00
    trigger: time
    id: Start working
  - at: 00:00:00
    trigger: time
    id: Stop working
  conditions:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Start working
      sequence:
      - action: switch.turn_on
        metadata: {}
        target:
          device_id: 2c680c927a635dca2b6704a9d8d15d09
        data: {}
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Stop working
      sequence:
      - action: switch.turn_off
        metadata: {}
        target:
          device_id: 2c680c927a635dca2b6704a9d8d15d09
        data: {}
  mode: single
- id: '1760733577087'
  alias: Familienbad - Heizkörper
  description: Sets heating to 22°C or Off based on a weekday/weekend schedule.
  triggers:
  - at: 05:45:00
    id: weekday_morning_on
    trigger: time
  - at: 08:00:00
    id: weekday_morning_off
    trigger: time
  - at: 07:00:00
    id: weekend_morning_on
    trigger: time
  - at: 09:30:00
    id: weekend_morning_off
    trigger: time
  - at: '18:30:00'
    id: evening_on
    trigger: time
  - at: '20:00:00'
    id: evening_off
    trigger: time
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: trigger
            id: weekday_morning_on
          - condition: time
            weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: and
          conditions:
          - condition: trigger
            id: weekend_morning_on
          - condition: time
            weekday:
            - sat
            - sun
        - condition: trigger
          id: evening_on
      sequence:
      - target:
          area_id: familienbad
          device_id: 75b7856de539d67a4d57d526f761dac0
        data:
          temperature: 22
          hvac_mode: heat
        action: climate.set_temperature
    - conditions:
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: trigger
            id:
            - weekday_morning_off
          - condition: time
            weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: and
          conditions:
          - condition: trigger
            id:
            - weekend_morning_off
          - condition: time
            weekday:
            - sat
            - sun
      sequence:
      - target:
          area_id: familienbad
          device_id: 75b7856de539d67a4d57d526f761dac0
        data:
          temperature: 20
          hvac_mode: heat
        action: climate.set_temperature
    - conditions:
      - condition: or
        conditions:
        - condition: trigger
          id: evening_off
      sequence:
      - target:
          area_id: familienbad
          device_id: 75b7856de539d67a4d57d526f761dac0
        data:
          hvac_mode: heat
          temperature: 18
        action: climate.set_temperature
  mode: single
- id: '1778187802092'
  alias: Waschmaschine Automatisch Aus
  description: ''
  use_blueprint:
    path: Fredrik81/powerplug-auto-shutdown.yaml
    input:
      power_sensor: sensor.strom_waschmaschine_power
      plug_switch: switch.strom_waschmaschine
      use_time_check: true
      enable_notification: false
      max_run_time: 10
      grace_period: 60
      watt_threshold: 1
