#+TITLE: Emacs Installation Instructions
#+PROPERTY: header-args :tangle install.sh :shebang #!/usr/bin/env bash

* Installation instructions

Currently, I use version 29.0.60 of Emacs. Here I describe on how to
build it by yourself, which is what I do to keep up with current
development on the Emacs master branch.

** My little helpers

Let's start off with some basic stuff and exit the script as soon as an
error occurs.

#+begin_src shell
  set -e
#+end_src

There are two options to get Emacs. The first one is to download the
source code from an official server.

The following code works for all officially released Emacs version.
It downloads and extracts Emacs.

#+begin_src shell
  download() {
      (
          __TMP_DIR="$(mktemp -d)"
          echo "Download Emacs ${__EMACS_VERSION} to ${__TMP_DIR}"

          cd "${__TMP_DIR}" || exit 1
          __EMACS_TAR_FILENAME="emacs-${__EMACS_VERSION}.tar.gz"
          wget "http://ftp.halifax.rwth-aachen.de/gnu/emacs/${__EMACS_TAR_FILENAME}"
          tar -xvf "${__EMACS_TAR_FILENAME}" -C "${__XDG_DATA_HOME}"
          if [ ! -d "${__EMACS_HOME}" ]
          then
              echo "Target folder ${__EMACS_HOME} does not exist. Extracting Emacs package failed."
              exit 1
          fi
      )
  }
  #+end_src

The following code allows you to clone a specific version of Emacs
that is tagged in the Savannah repository. Usually, when they create a
release branch I use this function to download it.

#+begin_src shell
  clone() {
      (
          git clone https://git.savannah.gnu.org/git/emacs.git "${__EMACS_HOME}"
          cd "${__EMACS_HOME}" || exit 1
          git checkout emacs-"${__EMACS_VERSION}"
      )
  }

  pull() {
      (
          cd "${__EMACS_HOME}" || exit 1
          git reset --hard HEAD
          git checkout emacs-"${__EMACS_VERSION}"
          git pull
      )
  }
#+end_src

Then, I install all the required third party dependencies and build Emacs

#+begin_src shell
  build() {
      (
          echo "Install dependencies for building Emacs ${__EMACS_VERSION}"

          sudo apt install libxpm-dev libgif-dev libjpeg-dev libpng-dev \
               libtiff-dev libx11-dev libncurses5-dev automake autoconf \
               texinfo libgtk2.0-dev libgtk-3-dev gcc-10 g++-10 libgccjit0 \
               libgccjit-10-dev libgccjit-9-dev libjansson4 \
               libjansson-dev libgnutls28-dev libacl1-dev libmagickwand-dev \
               libxml2-dev

          echo "Compile and install Emacs ${__EMACS_VERSION}"

          export CC=/usr/bin/gcc-10 CXX=/usr/bin/gcc-10
          cd "${__EMACS_HOME}" || exit 1
          ./autogen.sh
          ./configure --prefix "${__EMACS_HOME}" --bindir "${__EMACS_HOME}/bin" \
                      CFLAGS="-O3 -mtune=native -march=native -fomit-frame-pointer" \
                      --with-modules \
                      --with-gnutls \
                      --with-rsvg \
                      --with-x \
                      --with-json \
                      --with-mailutils \
                      --with-native-compilation \
                      --with-imagemagick \
                      --with-jpeg --with-png --with-rsvg --with-tiff \
                      --with-wide-int \
                      --with-xft \
                      --with-xml2 \
                      --with-xpm
          make -j"$(nproc)"
      )
  }
#+end_src

Finally, I make the new version globally available in your system
using update-alternatives.

#+begin_src shell
  install() {
      echo "Install Emacs and make it globally available with update-alternatives."

      (
          cd "${__EMACS_HOME}" || exit 1
          make install
      )

      sudo update-alternatives --install "/usr/bin/emacsclient" emacsclient "${__EMACS_HOME}/bin/emacsclient" 100
      sudo update-alternatives --install "/usr/bin/emacs" emacs "${__EMACS_HOME}/bin/emacs" 100
      sudo update-alternatives --auto emacs
      sudo update-alternatives --auto emacsclient
  }
#+end_src

Once you have Emacs installed, it configures it on its own at
startup.

Finally, we check whether the right Emacs version is installed or not

#+begin_src shell
  is_expected_emacs_version_installed() {
      __EMACS_VERSION_OUTPUT=$(emacs -Q --version | grep "${__EMACS_VERSION}")
      [[ "${__EMACS_VERSION_OUTPUT}" =~ "GNU Emacs ${__EMACS_VERSION}"* ]]
  }
#+end_src

and if the target directory, where Emacs should be installed, does
already exist or not.

#+begin_src shell
  exists_target_directory() {
      test -r "${__EMACS_HOME}"
  }
#+end_src

** Main

Here, we combine the little helper functions from the previous section
to install various versions of Emacs.

First, we use a command line argument parser to get the user defined
Emacs version. The default one is currently 29.0.60.

#+begin_src shell
  usage()
  {
      echo "Builds and installs Emacs"
      echo ""
      echo " -h --help:                 show this help"
      echo " -v --version               Emacs version to be installed."
      echo ""
  }

  # Emacs version to be installed
  __EMACS_VERSION="29"

  # Loop through arguments and process them
  while [ $# -gt 0 ]; do
      key="$1"
      case $key in
          -h | --help)
              usage
              exit
              ;;
          -v|--version)
              __EMACS_VERSION="$2"
              shift
              shift
              ;;
          ,*)
              echo "ERROR: unknown parameter $1"
              usage
              exit 1
              ;;
      esac
  done
  #+end_src

Then we set up a few variables that define the home directory of the
Emacs installation.

#+begin_src shell
  __XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
  __EMACS_HOME="${__XDG_DATA_HOME}/emacs-${__EMACS_VERSION}"
  [ ! -d "${__XDG_DATA_HOME}" ] && mkdir -p "${__XDG_DATA_HOME}"
#+end_src

Check if the given Emacs version is an official release. If so,
install it from one of the official release servers.

#+begin_src shell
  if [[ ${__EMACS_VERSION} =~ ^[0-9]+\.[0-9]+$ ]]
  then
      echo "Looks like an official Emacs version."

      if ( is_expected_emacs_version_installed )
      then
          echo "Emacs ${__EMACS_VERSION} is already installed. Nothing to be done here."
          exit 0
      fi

      if ( exists_target_directory )
      then
          echo "Target directory of Emacs sources does already exist."
          echo "Delete ${__EMACS_HOME} before you can continue here."
          exit 1
      fi

      download
  fi
#+end_src

If it is no official version, check for a release tag on the Savannah
repository and check it out.

#+begin_src shell
  if [[ ${__EMACS_VERSION} =~ ^[0-9]+$ ]]
  then
      echo "Looks like a tag version of the Emacs Savannah git repository."

      if [[ ! -d ${__EMACS_HOME} ]]
      then
          clone
      elif [[ -d "${__EMACS_HOME}/.git" ]]
      then
          pull
          rm -rf "${__EMACS_HOME}/bin"
      else
          echo "The target directory ${__EMACS_HOME} already exists but it is not a git repository."
          echo "Please remove it otherwise I can't continue."
      fi
  fi
#+end_src

If no Emacs version was found for the given tag, just stop here.

#+begin_src shell
  if [[ ! -d "${__EMACS_HOME}" ]]
  then
      echo "Unknown version tag. Only versions like 28.2 and 29 are supported."
      exit 1
  fi

#+end_src

Once we have the source code locally available, all that is left to do
is to build and to install it

#+begin_src shell
  build
  install
#+end_src

Check now again if the expected version of Emacs is installed

#+begin_src shell
  if ( is_expected_emacs_version_installed )
  then
      echo "Emacs ${__EMACS_VERSION} was successfully installed."
  else
      echo "Emacs ${__EMACS_VERSION} was not found."
      echo "Please check 'sudo update-alternatives --config emacs' for details."
  fi
#+end_src
