#+TITLE: Emacs Installation Instructions
#+PROPERTY: header-args :tangle install.sh :shebang #!/usr/bin/env bash

* Installation instructions

This document describes how I install Emacs. It supports two modes:

1. Installation of an official release: It downloads, extracts and
   installs a specified version that is pre-packed and available
   [[http://ftp.halifax.rwth-aachen.de/gnu/emacs][online.]]
2. Installation from feature branch of [[https://git.savannah.gnu.org/git/emacs.git][Savannah repository]]: It checks
   out the corresponding feature branch of Emacs, builds and installs
   it.

** My little helpers

Let's start off with some basic stuff and exit the script as soon as an
error occurs.

#+begin_src shell
  set -e
#+end_src

There are two options to get Emacs. The first one is to download the
source code from an official server.

The following code works for all officially released Emacs version.
It downloads and extracts Emacs.

#+begin_src shell
  download() {
      (
          __TMP_DIR="$(mktemp -d)"
          echo "Download Emacs ${__EMACS_VERSION} to ${__TMP_DIR}"

          cd "${__TMP_DIR}" || exit 1
          __EMACS_TAR_FILENAME="emacs-${__EMACS_VERSION}.tar.gz"
          wget "http://ftp.halifax.rwth-aachen.de/gnu/emacs/${__EMACS_TAR_FILENAME}"
          tar -xvf "${__EMACS_TAR_FILENAME}" -C "${__XDG_CACHE_HOME}"
          if [ ! -d "${__EMACS_SRC}" ]
          then
              echo "Source folder ${__EMACS_SRC} does not exist. Extracting Emacs package failed."
              exit 1
          fi
      )
  }
  #+end_src

The following code allows you to clone a specific version of Emacs
that is tagged in the Savannah repository. Usually, when they create a
release branch I use this function to download it.

#+begin_src shell
  clone() {
      (
          git clone https://git.savannah.gnu.org/git/emacs.git "${__EMACS_SRC}"
          cd "${__EMACS_SRC}" || exit 1
          git checkout emacs-"${__EMACS_VERSION}"
      )
  }

  pull() {
      (
          cd "${__EMACS_SRC}" || exit 1
          git reset --hard HEAD
          git checkout emacs-"${__EMACS_VERSION}"
          git pull
      )
  }
#+end_src

Then, I install all the required third party dependencies and build Emacs

#+begin_src shell
  build() {
      echo "Install dependencies for building Emacs ${__EMACS_VERSION}"
      sudo apt install -y \
           gcc-10 \
           g++-10 \
           libgccjit0 \
           libgccjit-10-dev \
           libgccjit-9-dev \
           libjansson4 \
           libjansson-dev \
           libacl1-dev \
           libmagickwand-dev \
           libxml2-dev \
           build-essential \
           libgtk-3-dev \
           libgnutls28-dev \
           libtiff-dev \
           libgif-dev \
           libjpeg-dev \
           libpng-dev \
           libxpm-dev \
           libncurses-dev \
           texinfo \
	   libsqlite3-dev

      if [ -d "${__EMACS_BUILD}" ]
      then
          echo "Remove existing Emacs installation ${__EMACS_BUILD}."
          rm -rf "${__EMACS_BUILD}"
      fi

      # Install tree-sitter
      # https://git.savannah.gnu.org/cgit/emacs.git/tree/admin/notes/tree-sitter/starter-guide?h=feature/tree-sitter
      (
          cd "${__XDG_CACHE_HOME}" || exit 1
          TREE_SITTER_DIR="tree-sitter"
          rm -rf "${TREE_SITTER_DIR}"
          git clone https://github.com/tree-sitter/tree-sitter.git "${TREE_SITTER_DIR}"
          cd "${TREE_SITTER_DIR}" || exit 1
          make clean
          make -j"$(nproc)"
          sudo make install
      )

      echo "Compile and install Emacs ${__EMACS_VERSION}"

      (
          cd "${__EMACS_SRC}" || exit 1
          export CC=/usr/bin/gcc-10 CXX=/usr/bin/gcc-10
          # clean everything before you start
          make clean
          # Make sure that treesitter lib is available to Emacs build
          # process
          export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}
          ./autogen.sh all
          ./configure --prefix "${__EMACS_BUILD}" \
                      --bindir "${__EMACS_BUILD}/bin" \
                      CFLAGS="-O3 -mtune=native -march=native -fomit-frame-pointer" \
                      --with-modules \
                      --with-gnutls \
                      --with-json \
                      --with-mailutils \
                      --with-native-compilation \
                      --with-imagemagick \
                      --with-rsvg --with-gif --with-jpeg --with-png --with-rsvg --with-tiff \
                      --with-wide-int \
                      --with-xft \
                      --with-xml2 \
                      --with-xpm \
                      --with-dbus \
                      --with-x \
                      --with-x-toolkit=gtk3 \
                      --with-native-compilation=aot \
                      --with-tree-sitter
          make -j"$(nproc)"
      )
  }
  #+end_src

Finally, I make the new version globally available in your system
using update-alternatives.

#+begin_src shell
  install() {
      echo "Install Emacs and make it globally available with update-alternatives."

      (
          cd "${__EMACS_SRC}" || exit 1
          make install
      )

      sudo update-alternatives --install "/usr/bin/emacsclient" emacsclient "${__EMACS_BUILD}/bin/emacsclient" 100
      sudo update-alternatives --install "/usr/bin/emacs" emacs "${__EMACS_BUILD}/bin/emacs" 100
      sudo update-alternatives --auto emacs
      sudo update-alternatives --auto emacsclient
  }
#+end_src

Once you have Emacs installed, it configures it on its own at
startup.

Finally, we check whether the right Emacs version is installed or not

#+begin_src shell
  is_expected_emacs_version_installed() {
      __EMACS_VERSION_OUTPUT=$(emacs -Q --version | grep "${__EMACS_VERSION}")
      [[ "${__EMACS_VERSION_OUTPUT}" =~ "GNU Emacs ${__EMACS_VERSION}"* ]]
  }
#+end_src

and if the source directory, where Emacs should be downloaded to, does
exist or not.

#+begin_src shell
  exists_src_directory() {
      test -r "${__EMACS_SRC}"
  }
#+end_src

** Main

Here, we combine the little helper functions from the previous section
to install various versions of Emacs.

First, we use a command line argument parser to get the user defined
Emacs version. The default one is currently 29.

#+begin_src shell
  usage()
  {
      echo "Builds and installs Emacs"
      echo ""
      echo " -h --help:                 show this help"
      echo " -v --version               Emacs version to be installed."
      echo ""
  }

  # Emacs version to be installed
  __EMACS_VERSION="29.1"

  # Loop through arguments and process them
  while [ $# -gt 0 ]; do
      key="$1"
      case $key in
          -h | --help)
              usage
              exit
              ;;
          -v|--version)
              __EMACS_VERSION="$2"
              shift
              shift
              ;;
          ,*)
              echo "ERROR: unknown parameter $1"
              usage
              exit 1
              ;;
      esac
  done
#+end_src

Then we set up a few variables that define the home directory of the Emacs installation.

#+begin_src shell
  __XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
  __XDG_CACHE_HOME="${XDG_CACHE_HOME:-${HOME}/.cache}"
  __EMACS_SRC="${__XDG_CACHE_HOME}/emacs-${__EMACS_VERSION}"
  __EMACS_BUILD="${__XDG_DATA_HOME}/emacs-${__EMACS_VERSION}"
  [ ! -d "${__XDG_DATA_HOME}" ] && mkdir -p "${__XDG_DATA_HOME}"
  [ ! -d "${__XDG_CACHE_HOME}" ] && mkdir -p "${__XDG_CACHE_HOME}"

#+end_src

Check if the given Emacs version is an official release. If so,
install it from one of the official release servers.

#+begin_src shell
  if [[ ${__EMACS_VERSION} =~ ^[0-9]+\.[0-9]+$ ]]
  then
      echo "Looks like an official Emacs version."

      if ( is_expected_emacs_version_installed )
      then
          echo "Emacs ${__EMACS_VERSION} is already installed. Nothing to be done here."
          exit 0
      fi

      if ( exists_src_directory )
      then
          echo "Source directory of Emacs does already exist."

          read -p "Do you want to delete ${__EMACS_SRC} [y/n]? " -n 1 -r
          echo    # (optional) move to a new line
          if [[ $REPLY =~ ^[Yy]$ ]]
          then
              # do dangerous stuff
        	    rm -rf "${__EMACS_SRC}"
          else
              echo "Delete ${__EMACS_SRC} before you can continue."
        	    exit 1
          fi
      fi

      download
  fi
#+end_src

If it is no official version, check for a release tag on the Savannah
repository and check it out.

#+begin_src shell
  if [[ ${__EMACS_VERSION} =~ ^[0-9]+$ ]]
  then
      echo "Looks like a tag version of the Emacs Savannah git repository."

      if [[ ! -d ${__EMACS_SRC} ]]
      then
          clone
      elif [[ -d "${__EMACS_SRC}/.git" ]]
      then
          pull
      else
          echo "The source directory ${__EMACS_SRC} already exists but it is not a git repository."
          echo "Please remove it before you can continute."
      fi
  fi
#+end_src

If no Emacs version was found for the given tag, just stop here.

#+begin_src shell
  if [[ ! -d "${__EMACS_SRC}" ]]
  then
      echo "Unknown version tag. Only versions like 28.2 (for official releases) and"
      echo " 29 (for feature branches that are named as \"emacs-<version>\") are supported."
      exit 1
  fi
#+end_src

Once we have the source code locally available, all that is left to do
is to build and to install it

#+begin_src shell
  build
  install
#+end_src

Check now again if the expected version of Emacs is installed

#+begin_src shell
  if ( is_expected_emacs_version_installed )
  then
      echo "Emacs ${__EMACS_VERSION} was successfully installed."
  else
      echo "Emacs ${__EMACS_VERSION} was not found."
      echo "Please check 'sudo update-alternatives --config emacs' for details."
  fi
#+end_src
