#+TITLE: Emacs Installation Instructions
#+PROPERTY: header-args :tangle install.sh :shebang #!/usr/bin/env bash

* Installation instructions

Currently, I use version 28.2 of Emacs. Here I describe on how to
build it by yourself, which is what I do to keep up with current
development on the Emacs master branch.

First, I download and extract the Emacs version I want to install. I
do so only if the current version is not yet installed.

#+begin_src shell
  # exit as soon as error occurs
  set -e

  __EMACS_VERSION="28.2"
  __XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
  __EMACS_HOME="${__XDG_DATA_HOME}/emacs-${__EMACS_VERSION}"
  [ ! -d "${__XDG_DATA_HOME}" ] && mkdir -p "${__XDG_DATA_HOME}"

  if [ ! -f "${__EMACS_HOME}/bin/emacs" ]; then
      (
          __TMP_DIR="$(mktemp -d)"
          echo "Download Emacs ${__EMACS_VERSION} to ${__TMP_DIR}"

          cd "${__TMP_DIR}" || exit 1
          __EMACS_TAR_FILENAME="emacs-${__EMACS_VERSION}.tar.gz"
          wget "http://ftp.halifax.rwth-aachen.de/gnu/emacs/${__EMACS_TAR_FILENAME}"
          tar -xvf "${__EMACS_TAR_FILENAME}" -C "${__XDG_DATA_HOME}"
          if [ ! -d "${__EMACS_HOME}" ]; then
              echo "Target folder ${__EMACS_HOME} does not exist. Extracting Emacs package failed."
              exit 1
          fi
      )
  #+end_src

The, I install all the third party dependencies required to build Emacs.

#+begin_src shell
    (
        echo "Install dependencies for building Emacs ${__EMACS_VERSION}"

        sudo apt install libxpm-dev libgif-dev libjpeg-dev libpng-dev \
             libtiff-dev libx11-dev libncurses5-dev automake autoconf \
             texinfo libgtk2.0-dev libgtk-3-dev gcc-10 g++-10 libgccjit0 \
             libgccjit-10-dev libgccjit-9-dev libjansson4 \
             libjansson-dev libgnutls28-dev libacl1-dev libmagickwand-dev \
             libxml2-dev
    )
#+end_src

To build Emacs, I run

#+begin_src shell
  (
      echo "Compile and install Emacs ${__EMACS_VERSION}"

      export CC=/usr/bin/gcc-10 CXX=/usr/bin/gcc-10
      cd "${__EMACS_HOME}" || exit 1
      ./autogen.sh
      ./configure --prefix "${__EMACS_HOME}" --bindir "${__EMACS_HOME}/bin" \
                  CFLAGS="-O3 -mtune=native -march=native -fomit-frame-pointer" \
                  --with-modules \
                  --with-gnutls \
                  --with-rsvg \
                  --with-x \
                  --with-json \
                  --with-mailutils \
                  --with-native-compilation \
                  --with-imagemagick \
                  --with-jpeg --with-png --with-rsvg --with-tiff \
                  --with-wide-int \
                  --with-xft \
                  --with-xml2 \
                  --with-xpm
      make -j"$(nproc)"
      make install
  )
#+end_src

Finally, make the new version globally available in your system using
update-alternatives.

#+begin_src shell

  (
      echo "Make Emacs available with update-alternatives."

      sudo update-alternatives --install "/usr/bin/emacsclient" emacsclient "${__EMACS_HOME}/bin/emacsclient" 100
      sudo update-alternatives --install "/usr/bin/emacs" emacs "${__EMACS_HOME}/bin/emacs" 100
      sudo update-alternatives --auto emacs
      sudo update-alternatives --auto emacsclient
  )
#+end_src

Close the global if for all these steps so that when tangling this
file, you get a valid shell script.

#+begin_src shell
fi
#+end_src

Once you have Emacs installed, it configures it on its own at
startup.

Finally, we check whether the right Emacs version is installed or not.

#+begin_src shell
  __EMACS_VERSION_OUTPUT=$(emacs -Q --version | grep "${__EMACS_VERSION}")
  if [ "${__EMACS_VERSION_OUTPUT}" = "GNU Emacs ${__EMACS_VERSION}" ]; then
      echo "Emacs was successfully installed."
  else
      echo "The expected version ${__EMACS_VERSION} of Emacs was not found."
      echo "Please check 'sudo update-alternatives --config emacs' for details."
  fi
#+end_src
