---

name: Configure
on:
  push:
  pull_request:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup git-user
        env:
          GIT_USER_NAME: "GitHub Actions Runner"
          GIT_USER_EMAIL: "actions@users.noreply.github.com"
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"
          git fetch --all
      - name: Configure dotfiles and install third-party dependencies
        run: |
          rm ~/.bashrc ~/.profile
          ./configure -i
      - name: Run Emacs
        run: |
          echo "------------------------------------------------"
          emacs --version
          echo "------------------------------------------------"
          printf "%s\n%s\n%s\n" "(add-to-list 'load-path \"~/.config/emacs\")" "(require 'early-init)" "(require 'init)" | tee "test.el"
          emacs --script "test.el"
          test $? -eq 0 || exit 1
