---

name: Configure
on:
  push:
    branches:
      - "nightly"
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup git-user
        env:
          GIT_USER_NAME: "GitHub Actions Runner"
          GIT_USER_EMAIL: "actions@users.noreply.github.com"
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"
          git fetch --all
      - name: Install base
        run: |
          ./configure --install-base --skip-stow
      - name: Install NPM
        run: |
          ./configure --install-npm --skip-stow
      - name: Install ZSH
        run: |
          ./configure --install-zsh --skip-stow
      - name: Install docker
        run: |
          ./configure --install-docker --skip-stow
      - name: Install qtile
        run: |
          ./configure --install-qtile --skip-stow
      - name: Install nyxt
        run: |
          ./configure --install-nyxt --skip-stow
      - name: Install Emacs
        run: |
          ./configure --install-emacs --skip-stow
      - name: Create symbolic links to home
        run: |
          rm ~/.bashrc ~/.profile
          ./configure
      - name: Run Emacs (minimal)
        env:
          LD_LIBRARY_PATH: /usr/lib:/usr/local/lib
        run: |
          echo "------------------------------------------------"
          emacs --version
          echo "------------------------------------------------"
          printf "%s\n%s\n%s\n" "(add-to-list 'load-path \"~/.config/minimal-emacs\")" "(require 'early-init)" "(require 'init)" | tee "test-minimal.el"
          emacs --script "test-minimal.el"
          test $? -eq 0 || exit 1
      - name: Run Emacs (full)
        env:
          LD_LIBRARY_PATH: /usr/lib:/usr/local/lib
        run: |
          echo "------------------------------------------------"
          emacs --version
          echo "------------------------------------------------"
          printf "%s\n%s\n%s\n" "(add-to-list 'load-path \"~/.config/emacs\")" "(require 'early-init)" "(require 'init)" | tee "test-full.el"
          emacs --script "test-full.el"
          test $? -eq 0 || exit 1
